#name: Deploy
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy-backend:
#    name: Create and publish docker image
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Install pnpm
#        uses: pnpm/action-setup@v4
#
#      - name: Use Node.js 20
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'pnpm'
#
#      - name: Build and publish
#        working-directory: apps/backend
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
#          DOCKER_REGISTRY: "<account_id>.dkr.ecr.eu-west-3.amazonaws.com"
#          DOCKER_IMAGE_NAME: "template-backend"
#        run: |
#          pnpm install --frozen-lockfile
#          pnpm run build
#          docker build . -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
#          aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
#          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
